FROM ubuntu:16.04
USER root
RUN apt-get update
RUN apt-get install -y python-tox pkg-config libvirt-dev python-dev libxslt1-dev zlib1g-dev

FROM python:2.7
COPY ./requirements /requirements
RUN pip install -r /requirements/dev-requirements.txt

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]